swhks(1) "github.com/shinyzenith/swhks" "General Commands Manual"

# NAME

swhks - Server for swhkd, used to run user level commands over IPC.

# SYNOPSIS

*swhks* [_flags_]

# AUTHORS

Maintained by Shinyzenith <aakashsensharma@gmail.com>, EdenQwQ <lsahlm1eden@gmail.com>, and Angelo Fallaria <ba.fallaria@gmail.com>.
For more information about development, see <https://github.com/waycrate/swhks>.

# SEE ALSO

	- *swhkd(1)*
	- *swhkd(5)*
	- *swhkd-keys(5)*
